
server:
  port: 9001

crypto:
  key: key-12#$%2-sjparkkaes256-gcmcryp


spring:
  servlet:
    multipart:
      # 멀티파트 업로드 지원여부 (default: true)
      enabled: true
      ## 파일의 최대 사이즈 (default: 1MB) 파일당 최대 파일 크기
      max-file-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/develop?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        #        format_sql: true
        default_batch_fetch_size: 100
        #        jdbc:
        #          batch_size: 100
        #          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    database: mysql
#    database-platform: com.sellermill.common.config.MySQLCustomDialect

binding:
  language:
    a: test1
    b: test2
    c: test3